# confimap_yaml
apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-config
 namespace: default
data:
 index.html: |
   <html>
   <head><title>Hello World</title></head>
   <body>
   <h1>Hello World 123456</h1>
   </body>
   </html>