apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-2
  namespace: argocd
spec:
  project: webapp
  source:
    path: apps/app2
    repoURL: https://github.com/kimhan9/eks-test.git
    targetRevision: HEAD
  destination:
    namespace: webapp
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true