apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-3
  namespace: argocd
spec:
  destination:
    namespace: webapp
    server: https://kubernetes.default.svc
  project: webapp
  source:
    path: argocd/example/app-of-app/webapp-3
    repoURL: https://github.com/foxutech/kubernetes.git
    targetRevision: HEAD