apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
 name: webapp
 namespace: argocd
spec:
 description: Project Alpha description
 sourceRepos:
  - "*"
 destinations:
  - server: "*"
    namespace: "*"
  #- namespace: sample-app
  #  server: https://kubernetes.default.svc
 clusterResourceWhitelist:
  - group: "*"
    kind: "*"
 namespaceResourceWhitelist:
  - group: "*"
    kind: "*"  