# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment2
 namespace: test
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx2
 template:
   metadata:
     labels:
       app: nginx2
   spec:
     containers:
     - name: nginx2
       image: nginx:latest
       ports:
       - containerPort: 80
       volumeMounts:
       - name: nginx-config-volume
         mountPath: /usr/share/nginx/html
     volumes:
     - name: nginx-config-volume
       configMap:
         name: nginx-config2